### PR TITLE
chore: Add Apache license

### LINKED ISSUE #190: Add Apache license into all font folders (This will live as a dual license with the OFL)
[LICENSE-Apache.txt](https://github.com/IBM/plex/files/2274564/LICENSE-Apache.txt)

### PR DESCRIPTION
**Pull request by alisonjoseph**
closes #190 

Adds the following license files to each font folder and main folder

`LICENSE-README.txt`
`LICENSE-APACHE.txt` (which is the same as LICENSE.txt in the main repo folder)
`LICENSE-OFL.tx`t 

@mjabbink @twardoch fyi

### CODE REVIEW

**Comment by mjabbink** [comment]
@alisonjoseph looks like there might be an extra space between tx and t

screen shot 2018-08-13 at 10 46 08 am

**Comment by mjabbink** [comment]
@alisonjoseph Will the licenses sit inside the individual font folders? If designers are downloading these folders from all over I think the license should not be disconnected from the font folders (OT, WOFF, TT). These fonts are for everyone many being people who are not developing product or digital experiences at all but rather books, environmental design and signage systems etc.

**Comment by mjabbink** [comment]
@alisonjoseph I see you mentioned "each font folder" so approved to rock forward.

**Comment by alisonjoseph** [comment]
Thats just a typo in the PR 😄 

and yes, the licenses were copied into each individual font folder. (WOFF, TTF etc)

**Comment by mjabbink** [comment]
Thanks @alisonjoseph!

**Pull request merged**
