### PR TITLE
feat(simplified-chinese): release V1.0

### PR DESCRIPTION
**Pull request by Palke**
**IBM PLEX SANS SC V1.0 - 2024-11-18**

• Added
- Support for Simplified Chinese (29562 glyphs per font)

@mattrosno please help with review of the Telemetry

### CODE REVIEW

**Comment by mattrosno** [comment]
Telemetry instrumentation looks good. I see the dependency was installed as `"@ibm/telemetry-js": "^1.6.1"`. The latest version is 1.8.0. My one recommendation would be to use the latest with `^1.8.0`.

**Comment by Palke** [comment]
> Telemetry instrumentation looks good. I see the dependency was installed as `"@ibm/telemetry-js": "^1.6.1"`. The latest version is 1.8.0. My one recommendation would be to use the latest with `^1.8.0`.

@mattrosno I have updated the telemetry version for this package. Worth to mention that other families will be updated in another PR. Thanks!

**Review by Dan-Pastrolin-IBM — APPROVED** [review]

**Comment by NightFurySL2001** [comment]
Is it ok to note out characters with immediate errors?

**Comment by Palke** [comment]
> Is it ok to note out characters with immediate errors?

@NightFurySL2001 most likely tomorrow we are releasing, if you could wait - or - open an issue ahead of it, would be fine. Thanks!

**Pull request merged**
