### PR TITLE
feat(update): Plex Sans Version 3

### PR DESCRIPTION
**Pull request by tw15egan**
This is a PR for moving what was in the `version 03.zip` folder I was given to the Plex repo

Tracking in: https://github.ibm.com/carbon/issues/issues/797

@seejamescode can you take a look at this and ensure everything is correct. Thanks

### CODE REVIEW

**Comment by seejamescode** [comment]
Looks okay to me since because no files are deleted! Are there any new typefaces, weights, or glyphs? If so, `scripts/data/` files need to be updated and a `npm run build` needs to happen.

**Comment by BoldMonday** [comment]
## [IBM PLEX SANS V3.0] - 2018-05-27
### Added
- Support for monotonic Greek (73 glyphs per font)
- Glyph /currency (0x00A4)
- Glyph /prime (0x2032)
  Referenced in [issue 145](https://github.com/IBM/plex/issues/145)
- Glyph /primedbl (0x2033)
  Referenced in [issue 145](https://github.com/IBM/plex/issues/145)

### Changed
- TrueType hinting for many glyphs has been refined. Thanks to Mike Duggan at Microsoft for reporting some!
- OpenType layout feature <mark> includes support for combining mark positioning on Cyrillic vowels
  Referenced in [issue 155](https://github.com/IBM/plex/issues/155)
- OpenType layout feature <mark> includes support for combining mark positioning on Greek vowels
- OpenType layout feature <ss01> includes alternate shape for Greek lowercase letter /alpha and related glyphs
- OpenType layout feature <salt> includes alternate shape for Greek lowercase letter /alpha and related glyphs
- Glyph /gcommaaccent (0x0123) uses /g.alt02 now (instead of /g)
- Glyph /gdotaccent (0x0121) uses /g.alt02 now (instead of /g)

### Fixed
- Errors in PS hint replacement in all files containing PostScript outlines
- Various small errors in mark positioning
- Various small errors in symmetry of shapes
- Various small errors in metrics

**Comment by BoldMonday** [comment]
@seejamescode: with this new release unicode ranges for IBM Plex Sans have changed. (Plex Sans Condensed, Serif and Mono remain unchanged.)

Greek has to be added:
```
U+037E
U+0384-038A
U+038C
U+038E-03A1
U+03A3-03CE```

**Comment by BoldMonday** [comment]
Also please note that Greek has become a seperate member in the split webfonts:
```
IBMPlexSans-Bold-Cyrillic.woff
IBMPlexSans-Bold-Greek.woff
IBMPlexSans-Bold-Latin1.woff
IBMPlexSans-Bold-Latin2.woff
IBMPlexSans-Bold-Latin3.woff
IBMPlexSans-Bold-Pi.woff
```

**Comment by tw15egan** [comment]
- Ran `npm run build` to create updated `css` files, and I can see Greek in there. 
- Updated `unicodes.js` and added Greek like so:
screen shot 2018-06-25 at 10 40 27 am
- Updated `families.js` and added Greek like so: 
screen shot 2018-06-25 at 10 42 14 am


Let me know if I am forgetting anything

**Comment by seejamescode** [comment]
You’ll wanna check that the CSS loads the fewest amount of files needed since there is a new unicode range. Try a webpage with just Latin1 glyphs and make sure it only downloads the Latin1 file in the network tab of Chrome. If not, the order of the unicode ranges are wrong.

Also, it looks like @BoldMonday added new glyphs to existing unicode ranges. So I would make sure those glyphs load the Plex version.

**Comment by BoldMonday** [comment]
That is a good one @seejamescode. Indeed the unicode-ranges for Latin 1 have slightly changed to incorporate the currency symbol:
```
# IBM Plex Sans V3.0 - Latin1
U+0000
U+000D
U+0020-007E
U+00A0-00A3
U+00A4-00FF
U+0131
U+0152-0153
U+02C6
U+02DA
U+02DC
U+2013-2014
U+2018-201A
U+201C-201E
U+2020-2022
U+2026
U+2030
U+2039-203A
U+2044
U+2074
U+20AC
U+2122
U+2212
U+FB01-FB02
```

**Comment by BoldMonday** [comment]
The other two new glyphs (prime and double prime) have been added to the Pi fonts:
```
# IBM Plex Sans V3.0 - Pi
U+0E3F
U+2032-2033
U+2070
U+2075-2079
U+2080-2081
U+2083
U+2085-2089
U+2113
U+2116
U+2126
U+212E
U+2150-2151
U+2153-215E
U+2190-2199
U+21A9-21AA
U+21B0-21B3
U+21B6-21B7
U+21BA-21BB
U+21C4
U+21C6
U+2202
U+2206
U+220F
U+2211
U+221A
U+221E
U+222B
U+2248
U+2260
U+2264-2265
U+25CA
U+2713
U+274C
U+2B0E-2B11
U+EBE1-EBE7
U+ECE0
U+EFCC
```

**Comment by tw15egan** [comment]
The Unicode ranges have been updated here: https://github.com/IBM/plex/pull/174/commits/28a00aee7487c4a48e2baace71f054324ca4b6be

**Comment by BoldMonday** [comment]
FYI @seejamescode @tw15egan  -- I did a small correction in the PostScript .vfb source files, and in the generated .otf font files. Please make sure you take the latest files from Box.

**Comment by alisonjoseph** [comment]
Hi @BoldMonday this has been passed along to me to work on (TJ is out on paternity leave). Can I get a link to the files from box?

**Comment by BoldMonday** [comment]
Hi @alisonjoseph, hopefully this will work:
https://ibm.box.com/s/7xcx6w4fj5sj1yfwc2h15is0gjejas02

Please make sure to download and store the files locally before putting them in the repository.

**Comment by alisonjoseph** [comment]
@BoldMonday The link you posted didn't work for me, maybe I don't have access? I have this link however, is this one not correct? https://ibm.ent.box.com/s/8o59wtv2kciu6y2t528udgrst2pr5rt2

**Comment by BoldMonday** [comment]
@alisonjoseph Ah. Don’t know why my link is not working. But luckily the one you have is correct.

**Comment by alisonjoseph** [comment]
I copied over the latest updates. Just want to be sure this looks correct before releasing anything. Looks like some glif files ended up getting deleted? @BoldMonday @seejamescode

**Comment by BoldMonday** [comment]
@alisonjoseph Is there a summary of some sorts? Reviewing the full diff is impossible. (I am not really familiar with GitHub I'm afraid. )

**Comment by BoldMonday** [comment]
@alisonjoseph This does not look good. The glif files are not supposed to be deleted.

It appears that you are copying directly from Box and not from a local copy (which I suggested to do). This is not the way to do update the repo. Ask @seejamescode -- he had this problem before.

**Comment by alisonjoseph** [comment]
Hmm, I definitely downloaded the files from box to my local computer first. Will follow up with James next week.

**Comment by BoldMonday** [comment]
AFAIK the issue is that files in Box are all being zipped in the background. And Box has problems "unzipping" .ufo files. As a result the .ufo file in the repo becomes a zipped binary which it should not be.
But I guess @seejamescode can explain this better.

**Comment by seejamescode** [comment]
^ What BoldMonday said. If you download the zip from box, it corrupts files. You have to use Box Sync or Drive to have the files locally.

**Comment by alisonjoseph** [comment]
Thanks, will sync box and try again.

**Comment by alisonjoseph** [comment]
@BoldMonday Are you able to give me access to the box folder so I can sync to my computer?  alison.joseph@us.ibm.com

**Comment by BoldMonday** [comment]
@alisonjoseph invite sent.

**Comment by BoldMonday** [comment]
This looks a lot better @alisonjoseph. :)

**Comment by seejamescode** [comment]
screen shot 2018-07-24 at 10 44 17 am

^ That many lines deleted concerns me that there are missing files since the previous release. If anything, doesn’t this update include more lines than the previous release?

**Comment by seejamescode** [comment]
It looks like `.glif` files inside of the `.ufo` files are being removed. I wonder if that means those files are corrupt in this PR.

**Comment by alisonjoseph** [comment]
The `.glif` files still seem like they aren't being downloaded locally for me when syncing box. I'm in a workshop the next 3 days so not sure how much time I'll have to dig into this right now. Will try opening those files that way though James, thanks.

**Comment by alisonjoseph** [comment]
still doesn't seem right. I'm getting errors syncing ufo files with box,I thought I fixed it by downloading each one individually, but looks like some files are still missing.

**Comment by BoldMonday** [comment]
@alisonjoseph Let's try something different. I have just deleted the following folders from Box:
- IBM-Plex-Sans
- IBM-Plex-Sans-Hebrew
I've replaced these with corresponding zip files that contain all latest files.
Please copy the zip files to somewhere local on your machine, unzip, and commit these.

**Comment by alisonjoseph** [comment]
Thanks, going to try a clean PR with all the updated files.

**Comment by alisonjoseph** [comment]
@BoldMonday Is there a reason there are no complete/split files for Hebrew? It looks like those were left out of TJs original PR, but wanted to double check if they should be added or not?

**Comment by alisonjoseph** [comment]
started over with a clean PR https://github.com/IBM/plex/pull/181

**Pull request closed without merging**
