### PR TITLE
[RFC] Add font face observer entry file and add example

### PR DESCRIPTION
**Pull request by joshblack**
Wanted to add a simple PR that adds in a simple `webpack` example in addition to a potential font loading strategy. This is totally an RFC (Request for comments) on this particular webfont loading approach, would love to hear more about what consumers would want and what we could provide them to make both them and our customers happy 😄 

For reference, the strategies that I experimented with are coming from [here](https://www.zachleat.com/web/comprehensive-webfonts).

## Motivation

This PR namely adds in the "FOUT with a Class" strategy that has the following characteristics:

### Pros

- Rendering performance: Eliminates FOIT. This method is tried and tested. It’s one of the approaches recommended by TypeKit.
- Flexibility: Easy to group requests into a single repaint (use one class for multiple web font loads)
- Scalability: Requests happen in parallel
- Robust: if the request fails, fallback text is still shown.
- Hosting: Works independent of font loader (easy to implement with third party hosts or with existing @font-face blocks)
- Great browser support, polyfills typically work everywhere that web fonts are supported.
- Future friendly: polyfills aren’t coupled to font formats and should work with existing @font-face blocks. That means when a new format comes out, you can just change your @font-face as normal.
- Does not require modification of the fonts (through subsetting or otherwise). Very license friendly.

### Cons

- Requires strict maintenance/control of your CSS. A single use of a web font font-family in your CSS without the guarding loaded class will likely trigger a FOIT.
- Typically requires you to hard code which web fonts you want to load on the page. This can mean that you end up loading more web font content than a page needs. Remember that with unceremonious @font-face usage, newer browsers only download web fonts that are actually used on your page. This is given to you for free. This is why the New York Times can get away with 100 different @font-face blocks on their home page—the browser only downloads a fraction of those. With this approach, you must tell the browser which fonts to download independent of usage.

It does it by adding in two new selectors, `ibm-type--loading` and `ibm-type--loaded`. The CSS defined by those selectors basically specify the fallbacks for the page while loading, and then uses `font-face-observer` to load in the fonts needed and then swap the class to `ibm-type--loaded` with the official font-stacks swapped in.

## Usage

From a developer perspective, we expose essentially all the potential font observers that they would want to use through the generated `lib/index.js` file. As a result, a developer would need to do the following:

```js
import { SansRegular, SansSemiBold, MonoRegular } from '@ibm/type';

const loadFonts = [SansRegular, SansSemiBold, MonoRegular]
  .map(font => font.load());

Promise.all(loadFonts)
  .then(() => {
    // Change class on `body` to `ibm-type--loaded`
  })
  .catch(error => {
    // Handle error loading font
  })
```

In addition, we've added in the `font-display` property on all `@font-face` declarations and updated the `url()` paths to be relative so that a developer can use tooling to read the font files and update the paths accordingly.

### CODE REVIEW

**Comment by joshblack** [comment]
Note: totally get that this breaks part of the existing repo. Figured I'd put up the approach early, get feedback, then circle back with an "official" PR 😄

**Comment by seejamescode** [comment]
If anyone is confused on the files changed page, [this bit](https://github.com/IBM/type/pull/46/files#diff-bcd1348a554e7e33c5c6fbb6b41c7eaaR825) on the compiled file is the important part.

I think personally think this is great and it is vital that it an opt-in strategy. Keep the barrier of entry low, but allow for great optimizations.

Leaving it open for a week for discussion.

**Comment by diego-codes** [comment]
This approach makes sense to me, if I understand it correctly.

From a developer perspective, if I don't want to/can't use this optimization, I would use the class  `.ibm-type--loaded`?

**Comment by seejamescode** [comment]
I think we switch `.ibm-type--loaded` to `.ibm-type` for default behavior. Then this loading strategy is opt-in.

**Comment by joshblack** [comment]
@seejamescode do we want the load strategy to be opt-in or the default? I think there are pretty good arguments for either which makes this really hard 😓

**Comment by seejamescode** [comment]
Can I see recordings of our options here? My assumption was that the options are:

- Master branch as-is
- Using this PR without using `lib/index.js`
- Using this PR and using `lib/index.js`

**Comment by diego-codes** [comment]
@joshblack I think that the performant approach should be the default/encouraged one. The nice thing about make it the default is that once `font-display` becomes more standardized, it will be easier to remove the javascript optimization for the FOUT with a class.

**Comment by seejamescode** [comment]
If we are going to implement a strategy, it is going to now happen directly in Carbon. Thanks for doing all of this work, @joshblack!

**Pull request closed without merging**
